### ISSUE TITLE
Support passing `is_autotest` to TestRun creation to all reporters

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-java#74]
It is possible to set `is_autotest` (boolean) property
https://developers.qase.io/reference/create-run

- cucumber3
- cucumber4
- cucumber5
- junit4
- junit5
- testng

**Comment by 1ivliev** [comment]
@mbirintsev Hi! I would like this property to be passed automatically (when creating a run via java integration), because it is a test run attribute.
<img width="665" alt="Screenshot 2022-09-14 at 09 26 14" src="https://user-images.githubusercontent.com/64368690/190076785-275d0220-fd54-458a-be87-d1a58158cfe7.png">

**Comment by mbirintsev** [comment]
@1ivliev ,

Thank you for the clarification! I will check and come back with a response (or even an implementation)

**Comment by mbirintsev** [comment]
@1ivliev ,

Let me share my thoughts about this.

I believe, the most straight and simple way to do this is to default [the field](https://github.com/qase-tms/qase-java/blob/master/qase-api/src/main/java/io/qase/client/model/RunCreate.java#L46) to `true`. Despite we can do it right here, manually, the changes will be outdated right the next (i.e. https://github.com/qase-tms/qase-java/issues/75) `io.qase.client.*` update (or we will be tied with keeping track on custom updates in the package, that sounds just weird).
So, I believe, we could assign the default value [over there](https://github.com/qase-tms/specs/raw/master/api.yaml) (the generated code source). However, I am not sure if other reporters (like JS, PHP, or .NET) will not be 'broken'. They do use the source as well, do not they?

If we set the default value in [the file](https://github.com/qase-tms/specs/raw/master/api.yaml), there will be no need to raise the same issue across other language reporters. Moreover, the default value will be "persisted" through the package updates.
So, my question is can we modify [the file](https://github.com/qase-tms/specs/raw/master/api.yaml) in order to set the default value to a `RunCreate` request?

Thank you!

**Comment by mbirintsev** [comment]
If the approach above is not appreciable, there is another one of just creating (e.g) `io.qase.api.defaults.RequestDefaults.createDefaultRunCreate()` that will serve as a java-local defaults overrider for [the configuration](https://github.com/qase-tms/specs/raw/master/api.yaml).

PS: this approach seems less "correct" because it spreads requests configuration.
